INFO     Run.py:test_CDk.py:49 正在发送请求
INFO     Run.py:test_CDk.py:53 响应结果：{'code': 500000, 'message': 'Recovery'}
ERROR    Run.py:test_CDk.py:59 断言错误：assert 500000 == 20000
INFO     Run.py:test_CDk.py:33 测试完成